### ISSUE TITLE
新版本似乎更换了抽卡服务器和数据服务器的地址

### ISSUE THREAD

**Issue by fux4** [guch8017/ArknightsGachaMonitor#1]
是否可以请求更新_(:3

**Comment by ZSCharlie** [comment]
附议

**Comment by fux4** [comment]
行吧，不知道是不是Charles的问题，今天又恢复正常了

**Comment by ZSCharlie** [comment]
我还是不行。。。方便留个联系方式吗

**Comment by guch8017** [comment]
新版本启用了secure连接，如果在开始游戏前的获取网络信息那里要求启用安全连接（secure键值为true）则游戏会采用内部虚拟路由绕过抓包，因此Charles无法获取数据。但是最近发现游戏仅在少数时候启用了安全链接，所以大部分时候还是可用的。
